changed publicKey to verificationMethod in test vectors
w3c-ccg/did-method-key pull request #48
Opened 2022-03-02 16:08 UTC by acarnagey

https://github.com/w3c-ccg/did-method-key/issues/34

2022-03-02 16:12 UTC, BenjaminMoe approved these changes

2022-03-02 16:25 UTC, OR13 approved these changes

2022-03-02 16:25 UTC, OR13 commented on index.html
>    "@context": "https://w3id.org/did/v1",
@acarnagey actually canyou fix this as well

2022-03-02 17:07 UTC, OR13 commented on index.html
>    "@context": "https://w3id.org/did/v1",
use https://did.key.transmute.industries/ and `application/did+ld+json`... consider adding data for the `did+json` and JWK format as well.

2022-03-02 17:07 UTC, OR13 requested changes
please fix the context issue as well.

2022-03-02 18:43 UTC, decentralgabe commented
thanks for this!

2022-03-03 15:39 UTC, OR13 approved these changes

2022-03-09 15:31 UTC, OR13 approved these changes

2022-03-09 15:32 UTC, merged